global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jobqueue-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  - job_name: 'jobqueue-workers'
    static_configs:
      - targets: ['worker:8001', 'worker-2:8001']
    metrics_path: /metrics
