apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobqueue-ingress
  namespace: jobqueue
  labels:
    app.kubernetes.io/name: jobqueue
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/websocket-services: "jobqueue-api-service"
spec:
  ingressClassName: nginx
  rules:
    - host: jobqueue.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobqueue-api-service
                port:
                  number: 80
