apiVersion: batch/v1
kind: Job
metadata:
  name: jobqueue-migrate
  namespace: jobqueue
  labels:
    app.kubernetes.io/name: jobqueue-migrate
    app.kubernetes.io/component: migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migrate
          image: localhost:5001/jobqueue-api:local
          imagePullPolicy: Never
          command: ["python", "-m", "alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jobqueue-secret
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: jobqueue-config
      restartPolicy: OnFailure
  backoffLimit: 3
